### PR TITLE
workflows: data and extra_data availability

### PR DESCRIPTION
**Pull request by jacquerie**
`get_formatted_data` makes those two attributes available in further calls, which I find a little confusing: just make those available from the start.

### CODE REVIEW

**Comment by jacquerie** [comment]
Uhm. Weird. Running `isort` worsened the order of the imports, according to `kwalitee`.

**Comment by tiborsimko** [comment]
`pytest-isort` and `flake8-import-order` do not agree with each other often...  A workaround is to decorate offending lines with `# noqa` and `# isort:skip`, until we standardise.

**Comment by jalavik** [comment]
Thanks @jacquerie, you can add `Reviewed-by: Jan Aage Lavik <jan.age.lavik@cern.ch>`

**Comment by jacquerie** [comment]
> you can add Reviewed-by: Jan Aage Lavik <jan.age.lavik@cern.ch>

:+1:

**Pull request merged**
